#!/bin/sh

jgit_home=`dirname $0`
cp="$jgit_home/org.spearce.jgit/bin"
cp="$cp:$jgit_home/org.spearce.jgit/lib/jsch-0.1.37.jar"
unset jgit_home
java_args=

# Cleanup paths for Cygwin.
#
case "`uname`" in
CYGWIN*)
	cp=`cygpath --windows --mixed --path "$cp"`
	;;
Darwin)
	if test -e /System/Library/Frameworks/JavaVM.framework
	then
		java_args='
			-Dcom.apple.mrj.application.apple.menu.about.name=JGit
			-Dcom.apple.mrj.application.growbox.intrudes=false
			-Dapple.laf.useScreenMenuBar=true
			-Xdock:name=JGit
		'
	fi
	;;
esac

CLASSPATH="$cp"
export CLASSPATH

java=java
if test -n "$JAVA_HOME"
then
	java="$JAVA_HOME/bin/java"
fi

exec "$java" $java_args org.spearce.jgit.pgm.Main "$@"
